## Python intermediate
<h2>Objectibes</h2>
<ol>
    <li>OOP (done)</li>
    <li>File handling (done)</li>
    <li>Try-Except (done)</li>
    <li>Web scrapping basic</li>
</ol>

## 1. OOP
Object Oriented Programming
Python is object oriented programming language since it use class and object to create something meaningful. 
Class is the blue print for the object

In [5]:
# Let's create a class and object in Python
class Student(object):
    def __init__(self, name, age): # This is called initialized object constructor
        self.name = name
        self.age = age

    def introduce(self): # This is method it give us more details about class
        return f"Hello, my name is {self.name} and I am {self.age} years old"

gatduel = Student("Gatduel", 27) # This is what we called object
print(gatduel.introduce())

Hello, my name is Gatduel and I am 27 years old

In [4]:
charles = Student("Charles", 25) # This is also another object
print(charles.introduce())

Hello, my name is Charles and I am 25 years old

## 2. File handling
Do you know that you can create, write, append and read notepad file using Python?
Today I will introduce you to opening and parsing file using Python with txt file and maybe in the future I will introduce you to CSV and JSON file.Parsing mean converting string file into list using the split method so that we can analyse them more easily

In [9]:
# Let's create a txt file using Python
with open("Desktop/GatduelR/example1.txt", "w") as file:
    filewrite = file.write("Gatduel know how to program using Python")
    filewrite1 = file.write("Gatduel is a PLP intern teaching database, webdev and Python")

In [15]:
# Now we read what is inside the file using Python
with open("Desktop/GatduelR/example1.txt", "r") as readfile:
    read = readfile.read(filewrite)
    readdata = readfile.read(filewrite1)

print(read)
print(readdata)

Gatduel know how to program using Python
Gatduel is a PLP intern teaching database, webdev and Python

## 3. try-except
In Python we have 3 types of errors
<ol>
    <li>Syntax errors</li>
    <li>Logic errors</li>
    <li>Exception errors</li>
</ol>
Here we will focus on how to handle exception in Python. Exception error occurs when we try to do the impossible in Python. If we try to do what is not in Python like opening a file without a real file path, use wrong data type to perform operation or dividing a number by zero. They are very many so you need to do research about them. Now try-except error prevent your code from crushing into exceptional errors, instead it provide a message that give the user clue that they have a mistake

In [19]:
# Here is the code without a try-except
name = input("What is your name? ") # accept only strings, if you try to put different data types the code will crush
age = int(input("How old are you? ")) # accept only integers, if you use non-integers the code will crush

print(f"My name is {name}")
print(f"I am {age} years old")

What is your name?  Gatduel
How old are you?  27

My name is Gatduel
I am 27 years old

In [37]:
# Here is the same code with try-accept, it prevent the whole program from code crush
try:
    student_name = input("What is your name? ") # The print function below the variable will prompt the user that this field contain string only
    
except:
    print("This field accept the string or text-only")
try:
    age = int(input("How old are you? "))

except: 
    print("The second line accept numbers only")
    
print(f"My name is {student_name}")
print(f"I am {age} years old")

What is your name?  Gatduel
How old are you?  wood

The second line accept numbers only
My name is Gatduel
I am 27 years old

## 4. Welcome to introduction to Web Scraping

<h3>Objectives</h3>
Today we are going to scrape some data using beautifusoup, requests, and structure it using pandas

If you want to know more about pandas, click the following link
<a href = "https://www.coursera.org/learn/python-for-applied-data-science-ai/lecture/yBbKS/pandas-loading-data" title = "Visit pandas tutorial" target = "_blank">Pandas Tutorial</a><br>
For more details about the request, visit this tutorial<br>
<a href = "https://www.coursera.org/learn/python-for-applied-data-science-ai/lecture/W6xwd/rest-apis-http-requests-part-1" title = "Visit requests tutorial" target = "_blank">Requests library tutorial part 1</a><br>
<a href = "https://www.coursera.org/learn/python-for-applied-data-science-ai/lecture/h9CR3/rest-apis-http-requests-part-2" title = "Visit requests tutorial" target = "_blank">Requests library tutorial part 2</a>

<h3>Web scraping libraries</h3>
<p>What is exactly web scraping?</p>
Web scraping, also known as web harvesting or web extraction, is the process of extracting or scraping data from a website and exporting it to different file formats like CSV, XLSX, JSON, SQL, and more. The scraped data can be used to know what is trending in social media and business. The data can also be used for Data analysis, Machine learning model training, Deep learning, and artificial intelligence training. Data and Web scraping are part or branch of Data Science called data engineering. For you to analyse data and train ML short for machine learning you need to have data, and that is where web and data scraping come in. This is a modern career, and it is growing every day.
<p>The following are libraries used for data and web scraping</p>
<ol>
    <li>BeautifulSoup</li>
    <li>Selenium</li>
    <li>Scrapy and</li>
    <li>Pandas</li>
</ol>
In this tutorial, we will focus on BeautifulSoup in combination with Pandas for structure and the requests library for API connection. Pandas can also be used to scrape tables in Website, and Selenium is used to scrape dynamic websites, while Scrapy is used for large-volume scraping.
In advance Web scraping, I will take you through Selenium, and I encourage you to explore Scrapy on your own if you are willing

## To scrape data you need to import the libraries

In [1]:
# Import libraries
import pandas as pd
import requests
from bs4 import BeautifulSoup

<p><b>The header variable prevents your scraping from being blocked, and the URL variable contains the URL 
of the websites you want to scrape. Scraping is for automation; it is like sending a robot to the website to fetch some data for you</b></p>

<p>To start practicing web scraping visit this url <a href = "https://www.scrapethissite.com/pages/" title = "Web scraping site" target = "_blank">Web Scraping site</a>
</p>

In [2]:
# Header and URL variables: I am scraping countries of the world
Header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/152.0.0.0 Safari/537.36"}
page_url = "https://www.scrapethissite.com/pages/simple/"

In [4]:
# Work with the requests library to download the structure of the website content
page = requests.get(page_url, headers = Header)

In [9]:
# Check the status of your website; if it is 200, it means you can scrape the website
page
# Since our status is 200 now, we can move on and scrape the data

In [19]:
# Use BeautifulSoup to parse the HTML contents
soup = BeautifulSoup(page.text, "html.parser")
#soup

In [20]:
# Now scrape the names of the countries
Title = soup.find_all("h3")
#Title

In [25]:
country_names = [headers.text.strip() for headers in Title]
#country_names

In [26]:
# Now let's scrape the page's capital cities
capital = soup.find_all("span", class_ = "country-capital")

In [30]:
country_capital = [city.text.strip() for city in capital]
#country_capital

In [31]:
# Let's scrape the population
ppl = soup.find_all("span", class_ = "country-population")

In [32]:
country_popula = [popu.text.strip() for popu in ppl]

In [47]:
# Lastly, let's scrape the area in km2 of the countries
country_area = soup.find_all("span", class_ = "country-area")

In [48]:
# Iterate through the data and add it to the variable
Area = [area.text.strip() for area in country_area]
Area

['468.0',
 '82880.0',
 '647500.0',
 '443.0',
 '102.0',
 '28748.0',
 '29800.0',
 '1246700.0',
 '1.4E7',
 '2766890.0',
 '199.0',
 '83858.0',
 '7686850.0',
 '193.0',
 '1580.0',
 '86600.0',
 '51129.0',
 '431.0',
 '144000.0',
 '30510.0',
 '274200.0',
 '110910.0',
 '665.0',
 '27830.0',
 '112620.0',
 '21.0',
 '53.0',
 '5770.0',
 '1098580.0',
 '328.0',
 '8511965.0',
 '13940.0',
 '47000.0',
 '49.0',
 '600370.0',
 '207600.0',
 '22966.0',
 '9984670.0',
 '14.0',
 '2345410.0',
 '622984.0',
 '342000.0',
 '41290.0',
 '322460.0',
 '240.0',
 '756950.0',
 '475440.0',
 '9596960.0',
 '1138910.0',
 '51100.0',
 '110860.0',
 '4033.0',
 '444.0',
 '135.0',
 '9250.0',
 '78866.0',
 '357021.0',
 '23000.0',
 '43094.0',
 '754.0',
 '48730.0',
 '2381740.0',
 '283560.0',
 '45226.0',
 '1001450.0',
 '266000.0',
 '121320.0',
 '504782.0',
 '1127127.0',
 '337030.0',
 '18270.0',
 '12173.0',
 '702.0',
 '1399.0',
 '547030.0',
 '267667.0',
 '244820.0',
 '344.0',
 '69700.0',
 '91000.0',
 '78.0',
 '239460.0',
 '6.5',
 '2166086.0',
 '11300.0',
 '245857.0',
 '1780.0',
 '28051.0',
 '131940.0',
 '3903.0',
 '108890.0',
 '549.0',
 '36120.0',
 '214970.0',
 '1092.0',
 '412.0',
 '112090.0',
 '56542.0',
 '27750.0',
 '93030.0',
 '1919440.0',
 '70280.0',
 '20770.0',
 '572.0',
 '3287590.0',
 '60.0',
 '437072.0',
 '1648000.0',
 '103000.0',
 '301230.0',
 '116.0',
 '10991.0',
 '92300.0',
 '377835.0',
 '582650.0',
 '198500.0',
 '181040.0',
 '811.0',
 '2170.0',
 '261.0',
 '120540.0',
 '98480.0',
 '17820.0',
 '262.0',
 '2717300.0',
 '236800.0',
 '10400.0',
 '616.0',
 '160.0',
 '65610.0',
 '111370.0',
 '30355.0',
 '65200.0',
 '2586.0',
 '64589.0',
 '1759540.0',
 '446550.0',
 '1.95',
 '33843.0',
 '14026.0',
 '53.0',
 '587040.0',
 '181.3',
 '25333.0',
 '1240000.0',
 '678500.0',
 '1565000.0',
 '254.0',
 '477.0',
 '1100.0',
 '1030700.0',
 '102.0',
 '316.0',
 '2040.0',
 '300.0',
 '118480.0',
 '1972550.0',
 '329750.0',
 '801590.0',
 '825418.0',
 '19060.0',
 '1267000.0',
 '34.6',
 '923768.0',
 '129494.0',
 '41526.0',
 '324220.0',
 '140800.0',
 '21.0',
 '260.0',
 '268680.0',
 '212460.0',
 '78200.0',
 '1285220.0',
 '4167.0',
 '462840.0',
 '300000.0',
 '803940.0',
 '312685.0',
 '242.0',
 '47.0',
 '9104.0',
 '5970.0',
 '92391.0',
 '458.0',
 '406750.0',
 '11437.0',
 '2517.0',
 '237500.0',
 '88361.0',
 '1.71E7',
 '26338.0',
 '1960582.0',
 '28450.0',
 '455.0',
 '1861484.0',
 '449964.0',
 '692.7',
 '410.0',
 '20273.0',
 '62049.0',
 '48845.0',
 '71740.0',
 '61.2',
 '196190.0',
 '637657.0',
 '163270.0',
 '644329.0',
 '1001.0',
 '21040.0',
 '21.0',
 '185180.0',
 '17363.0',
 '430.0',
 '1284000.0',
 '7829.0',
 '56785.0',
 '514000.0',
 '143100.0',
 '10.0',
 '15007.0',
 '488100.0',
 '163610.0',
 '748.0',
 '780580.0',
 '5128.0',
 '26.0',
 '35980.0',
 '945087.0',
 '603700.0',
 '236040.0',
 '0.0',
 '9629091.0',
 '176220.0',
 '447400.0',
 '0.44',
 '389.0',
 '912050.0',
 '153.0',
 '352.0',
 '329560.0',
 '12200.0',
 '274.0',
 '2944.0',
 '10908.0',
 '527970.0',
 '374.0',
 '1219912.0',
 '752614.0',
 '390580.0']

## Pandas territory

In [79]:
# Now let's create our data structure using a Pandas DataFrame
df = pd.DataFrame()
df["Country Names"] = country_names
df["Capital Cities"] = country_capital
df["Country Populations"] = country_popula
df["Country Area in km2"] = Area

In [50]:
# Let's check the first 5 rows
df.head()

,Country Names,Capital Cities,Country Populations,Country Area in km2
0,Andorra,Andorra la Vella,84000,468.0
1,United Arab Emirates,Abu Dhabi,4975593,82880.0
2,Afghanistan,Kabul,29121286,647500.0
3,Antigua and Barbuda,St. John's,86754,443.0
4,Anguilla,The Valley,13254,102.0

In [40]:
# Here we are checking for the number value and check their average
df.isna().mean()

Country Names          0.0
Capital Cities         0.0
Country Populations    0.0
Country Area in km2    0.0
dtype: float64

In [43]:
# Here we are checking for the highest population
df["Country Populations"].max()

'99900177'

In [51]:
# Let's check for the least population
df["Country Populations"].min()

'0'

In [55]:
# Let's calculate the total population of the world
#df["Country Populations"].mean()

In [64]:
df.dtypes

Country Names          object
Capital Cities         object
Country Populations    object
Country Area in km2    object
dtype: object

In [61]:
df.dtypes

Country Names          object
Capital Cities         object
Country Populations    object
Country Area in km2    object
dtype: object

In [69]:
# Converting text data which are also known as string or object to float which is a number with a decimal points
df[["Country Populations", "Country Area in km2"]] = df[["Country Populations", "Country Area in km2"]].astype("float64")

In [68]:
# Check the data types of columns inside Pandas
df.dtypes

Country Names           object
Capital Cities          object
Country Populations    float64
Country Area in km2    float64
dtype: object

In [70]:
# Check the size of the dataframe in pandas
df.size

1000

In [71]:
# Check the shape of the pandas dataframe
df.shape

(250, 4)

In [72]:
# Check the summary using describe function
df.describe()

       Country Populations  Country Area in km2
count         2.500000e+02         2.500000e+02
mean          2.744568e+07         5.996369e+05
std           1.168626e+08         1.911821e+06
min           0.000000e+00         0.000000e+00
25%           1.798562e+05         1.174750e+03
50%           4.288138e+06         6.489450e+04
75%           1.542062e+07         3.726315e+05
max           1.330044e+09         1.710000e+07

In [73]:
 # You can include all to describe the hidden details
df.describe(include = "all")

       Country Names Capital Cities  Country Populations  Country Area in km2
count            250            250         2.500000e+02         2.500000e+02
unique           250            242                  NaN                  NaN
top          Andorra           None                  NaN                  NaN
freq               1              8                  NaN                  NaN
mean             NaN            NaN         2.744568e+07         5.996369e+05
std              NaN            NaN         1.168626e+08         1.911821e+06
min              NaN            NaN         0.000000e+00         0.000000e+00
25%              NaN            NaN         1.798562e+05         1.174750e+03
50%              NaN            NaN         4.288138e+06         6.489450e+04
75%              NaN            NaN         1.542062e+07         3.726315e+05
max              NaN            NaN         1.330044e+09         1.710000e+07

In [74]:
# You can also check the information of your data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country Names        250 non-null    object
 1   Capital Cities       250 non-null    object
 2   Country Populations  250 non-null    float64
 3   Country Area in km2  250 non-null    float64
dtypes: float64(2), object(2)
memory usage: 7.9+ KB

In [75]:
# You can now calculate the total world population
df["Country Populations"].sum()

np.float64(6861418895.0)

In [77]:
# Calculate the average of the world population
df["Country Populations"].mean()

np.float64(27445675.58)

In [78]:
# You can also confirm that you are working with a pandas dataframe
type(df)

pandas.core.frame.DataFrame

In [83]:
# Now you can export your data to an Excel file, CSV, JSON, or SQL file. I will use Excel for now
df.to_excel("countries_data.xlsx", index = False)

In [1]:
## Write file in Python
with open("example.txt", "w") as writefile:
    write = writefile.write("This is example of writing file in Python")

In [3]:
with open("example.txt", "r") as readfile:
    read = readfile.read()

This is example of writing file in Python

In [15]:
readfile.mode

'r'

In [16]:
readfile.name

'example.txt'

In [17]:
readfile.encoding

'cp1252'

In [5]:
## Appending in Python
with open("example.txt", "a") as appendfile:
    append = appendfile.write("I am learning Python appending file.")

36

In [18]:
appendfile.mode

'a'

In [19]:
# Check file name
appendfile.name

'example.txt'

In [35]:
# Read the content of the txt file again
with open("example.txt", "r") as readfile:
    split_read = readfile.read()
type(split_read)

str

In [34]:
# Parsing in Python
split = split_read.split(",")
type(split)

list

In [13]:
fruit = ["Banana", "Jackfruit", "Mango"]
print(f"These are fruits before appending: {fruit}")
fruit.append(["Lemon", "Orange"])
print(f"These are fruits after appending: {fruit}")

These are fruits before appending: ['Banana', 'Jackfruit', 'Mango']
These are fruits after appending: ['Banana', 'Jackfruit', 'Mango', ['Lemon', 'Orange']]

In [24]:
# Copy the content of list to a file using for loop
Lines = ["Hello", "123", "Gatduel", "Charles"]
with open("anotherfile.txt", "w") as file:
    for name in Lines:
        file.write(name)

In [27]:
# Read the content of the anotherfile.txt
with open("anotherfile.txt", "r") as file:
    read = file.read()

print(read.split(","))

['Hello123GatduelCharles']